[workspace]
resolver = "2"
members = [
    "packages/neociv-app",
    "packages/neociv-bin",
    "packages/neociv-civil",
    "packages/neociv-config",
    "packages/neociv-game",
    "packages/neociv-macros",
    "packages/neociv-state"
]

