[config]
default_to_workspace = false

[env]
NEOCIV_CONTENT_ROOT = "${CARGO_MAKE_WORKING_DIRECTORY}/content"
CARGO_MAKE_COVERAGE_PROVIDER = "tarpaulin"

[tasks.coverage-tarpaulin]
clear = true
command = "cargo"
args = ["tarpaulin", "-o", "html", "--output-dir", "target/tarpaulin"]

[tasks.example-random-grid]
command = "cargo"
args = ["run", "--example", "random-grid"]
