[package]
name = "neociv-game"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8.0", features = ["bevy_render"] }
bevy_mod_picking = "0.8.0"
neociv-state = { path = "../neociv-state" }
neociv-civil = { path = "../neociv-civil" }
