[package]
name = "neociv-game"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy = { version = "0.9.1", features = ["bevy_render"] }
bevy_egui = "0.18.0"
bevy_mod_picking = "0.10.0"
egui_node_graph = "0.4.0"
fluent = "0.16.0"
neociv-state = { path = "../neociv-state" }
neociv-civil = { path = "../neociv-civil" }
