[package]
name = "neociv-civil"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neociv-state = { path = "../neociv-state" }
rlua = "0.19.1"
indoc = "1.0.7"
