[package]
name = "neociv-state"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_math = "0.8.0"
strum = { version = "0.24.0", features = ["derive"] }
num-integer = "0.1.44"
regex = "1.5.5"
lazy_static = "1.4.0"
serde = "1.0.143"
serde_json = "1.0.83"
rlua = "0.19.1"
