[package]
name = "neociv-launcher"
version = "0.0.1"
edition = "2021"

[dependencies]
eframe = { version = "0.22.0", features = ["wgpu"] }
egui = "0.22.0"
egui_dock = "0.6.3"
egui_extras = { version = "0.22.0", features = ["svg"] }
egui-wgpu = "0.22.0"